docs/api/storage/index.md

Fixed the path in the storage docs...

Fix path to localfilesystem.js in the doc

---

_includes/header.html
_plugins/relative-urls-to-absolute.rb
feed.xml

- add meta tag to blog for discoverability of feed
- add custom plugin to fix relative urls in post content
Screenshot of viewing the feed in Reeder.app:
[Example feed XML](https://gist.github.com/boneskull/2481b637f7d927280628b5673e02bfbd)

add atom (rss) feed

---

_includes/footer.html
community/index.md

Added a community page and a link to Node-RED User Group Japan.

Added a community page

---

docs/platforms/aws.md

Now has both ubuntu and EBS install instructions

Added documentation on how to run in AWS EBS

---

index.html

Hi there,
this PR fixes a dead link on the new page. I guess it should redirect to github.com?

fixed dead link

---

docs/platforms/bluemix.md
slack/index.html

As discussed bluemix upgrade - disable cache docu

bluemix upgrade - disable cache

---

_includes/docs-toc.html
_includes/getting-started-toc.html
docs/getting-started/installation.md
docs/platforms/windows.md

Added windows installation instructions as discussed on slack.  Added links in appropriate toc locations

add windows install and run instructions

---

docs/getting-started/installation.md

Also remove note about node-gyp as discussed with @dceejay

reference windows install in callout on main install page

---

README.md

add some info on how to test the site locally, point to mailing list, slack and wiki to contribute larger changes.

updated README to include how to preview the site

---

_posts/2016-10-17-js-foundation.md

Fix "Page not found" error

---

docs/configuration.md
docs/user-guide/index.md
docs/user-guide/projects/index.md

Address #69 by adding some comments to index, config and project section about basic knowledge of Javascript assumed.

add notes on requiring some javascript, modifying objects

---

docs/platforms/aws.md

This PR just fixes a broken link in the docs

Fix broken link in aws.md

---

docs/getting-started/installation.md

update supported node.js version

---

docs/getting-started/local.md
docs/user-guide/node-red-admin.md

I fixed broken links on nodered.org website.

Fix broken links

---

docs/user-guide/runtime/configuration.md

Current main.js doesn't contain loadEditor(). Therefore, I changed the file path to the correct one.

Fix file path in the document for configuration

---

docs/creating-nodes/first-node.md

https://nodered.org/docs/creating-nodes/first-node#lower-casespecjs
* Fix node module name (``node-red-test-helper`` to ``node-red-node-test-helper``)
* Remove unnecessary require "should".

Improve test code

---

docs/getting-started/docker.md

Adding in a Dockerfile pattern I've been using with Node-RED after having discussed this a bit over on Slack.

Adding some Dockerfile instructions

---

docs/creating-nodes/packaging.md

This PR updates the documentation on packaging of contribution nodes with the information on the changed/updated submission process for new and updated nodes.

Updated information on indexing of the flows library

---

docs/getting-started/docker.md

Fixing links for references for user permission errors

Fixing links for user permission errors

---

docs/getting-started/aws.md

This PR fixes running on AWS docs grammatical errors.

Fix running on AWS docs grammatical errors

---

docs/getting-started/beaglebone.md

This PR fixes beaglebone doc grammatical errors.

Fix beaglebone doc grammatical errors

---

docs/getting-started/docker.md

This PR fixes docker doc grammatical errors.

Fix docker doc grammatical errors

---

docs/getting-started/ibmcloud.md

This PR fixes IBM cloud doc grammatical errors.

Fix ibm-cloud doc grammatical errors

---

docs/api/admin/errors.md
docs/api/admin/oauth.md
docs/api/admin/types.md

This PR fixes admin-docs grammatical errors.

Fix admin-docs grammatical errors

---

docs/api/ui/editableList/index.md
docs/api/ui/searchBox/index.md
docs/api/ui/treeList/index.md

This PR fixes ui-docs grammatical errors.

Fix ui-docs grammatical errors

---

docs/creating-nodes/appearance.md

This PR fixes appearance doc grammatical errors.

Fix appearance doc grammatical errors

---

docs/creating-nodes/credentials.md
docs/creating-nodes/edit-dialog.md
docs/creating-nodes/first-node.md

This PR fixes creating-nodes docs grammatical errors.

Fix creating-nodes docs grammatical errors

---

docs/creating-nodes/help-style-guide.md
docs/creating-nodes/node-html.md

This PR fixes style-guide doc grammatical errors.

Fix style-guide doc grammatical errors

---

docs/creating-nodes/node-js.md
docs/creating-nodes/properties.md

This PR fixes properties doc grammatical errors.

Fix properties doc grammatical errors

---

docs/api/ui/editableList/index.md

Hi Nick/Dave,
I have added some documentations for the new custom buttons feature in the editableList.
Bart

EditableList custom buttons

---

docs/user-guide/writing-functions.md

Implementing PR: https://github.com/node-red/node-red/pull/2918
Not yet published, but merged - should be available in version 1.3.

Describe `node.outputCount` for function nodes

---

docs/user-guide/runtime/configuration.md

Hi,
This PR adds a missing configuration field. Not sure if the relative path will work though.
Thanks

Add functionExternalModules property to configuration

---

docs/getting-started/docker.md

The example on the getting started page talks about host directories but actually creates a named volume.
I've updated the command breakdown to correctly mention volumes. There are 2 sections later in the doc that discuss in detail how to mount a local directory or how to create new named volumes.

Update Docker volume information

---

docs/tutorials/second-flow.md

I was going through the docs and noticed that step 6 was missing in the second flow tutorial, so I fixed the numbering. By the way, the documentation is amazing! It's been a pleasure learning so far. Thank you! ❤️

Fix numbering in second flow tutorial

---

Gemfile
README.md

Added webrick to gemfile, needed in for Jekyll on ruby 3.x  (https://github.com/jekyll/jekyll/issues/8523)
Also added bundle install to the readme  for 1st time users

Updates for Ruby 3.0.0 and 1st time run

---

docs/user-guide/environment-variables.md

The current user guide lacks explanations of  new features of environment variable.
This PR adds these explanations to the user guide.

Add description of new environment variable features

---

docs/faq/interacting-with-arduino.md

Add Arduino Cloud option as integration method, with link to specific dedicated nodes

Add Arduino Cloud option as integration method

---

docs/user-guide/nodes.md

Hi, i'm developing an "overlay" for node-red that enables a webapp to show dashboards for interacting with flows and edit a flow in a react webapp project.
The inject core node guide line don't mention a lot about the API for the inject node, so i thought i'd supply it.
i really needed this information at this specific spot, and i had to look long to find it elsewhere, hope this helps out others who also wonder about the inject node  API.

updated your guidelines for core node "inject"

---

docs/tutorials/first-flow.md

Several people seem to have trouble getting the debug output in this first tutorial 
https://discourse.nodered.org/t/no-debug-output-in-side-bar-tried-lots-stuck-please-help/12418/64
For me this was due to a not so careful reading of step 5 and that one has to click the inject button. Therefore, I propose we make this explicit to avoid some newbie problems.

Separate step 5 of first tutorial into two steps for clarity

---

docs/api/ui/themes/index.md

Fix link to Monaco Editor construction options

---

_posts/2022-01-31-introducing-scorecard.md
docs/api/context/methods/index.md
docs/api/ui/treeList/index.md
docs/creating-nodes/help-style-guide.md
docs/creating-nodes/i18n.md
docs/faq/interacting-with-arduino.md
docs/user-guide/runtime/securing-node-red.md

This PR fixes a few typos found in documentation markdown files.

Fixing typos

---

index.html

As FRED doesn't allow new customers I've removed it from the list

Remove FRED from list of providers

---

docs/getting-started/flowforge.md
docs/getting-started/index.md

Updated FlowForge getting started page to include FlowForge Cloud.

Update to FlowForge getting started page

---

_posts/2023-02-24-community-survey

A blog post to announce a new Node-RED community survey.

Blog post to announce 2023 community survey.

---

about/community/survey/2023/charts.js
about/community/survey/2023/comments.json
about/community/survey/2023/data-2023.json
about/community/survey/2023/index.md

This is a write up of the 2023 community survey - thanks to @iskerrett for pulling this together.
This an initial PR that adds the survey results, but doesn't link to it anywhere - this is to allow for initial sharing and review before posting to the wider community.

Add initial draft of survey results

---

docs/api/admin/methods/post/nodes/index.md

Document how to install a TGZ npm bundle via the API

Add description of TGZ install options

---

docs/user-guide/runtime/securing-node-red.md

fixes https://github.com/node-red/node-red/issues/4952

Add refrene to `autoLogin`

---

docs/user-guide/runtime/configuration.md

Just switch to https instead of http.

Fix: use https for nodejs.org

---

_data/contributors.yml
_data/users.yml
about/index.md
css/front.css
index.html

Have done a small design refresh of the home page - it was feeling a bit old and clunky. There's still plenty of room for improvement, but its a start.
- Moved some of the previous content over to the About page
- Added a contributors section. I've picked out our more active contributors as well as those who have made significant contributions in the project's history. WIll need to think about how to best, and fairly, keep that up to date. I hope this is a fair first pass.
- Rewords how the 'users' grid is generated - now done via a yml data file. Planning to do a bit more of a reorg on that list to try to classify the types of use... but saving that for another day.

Refresh home page

---

_includes/header.html

Add a banner for the survey. Replaces #386 
fyi @dimitrieh

Add survey banner
