node-red/node-red.github.io

docs/api/runtime/api.md

The code uses singular, not plural. (Even though the function does accept multiple permissions in the form of an array.)

Fixes erroneous plural in RED.auth.needsPermission

---

docs/getting-started/adding-nodes.md

Fix a minor typo in the documentation:
To to this.. -> To do this..
Signed-off-by: Abdur Rehman <abdur_rehman@mentor.com>

adding-nodes.md: fix a typo

---

docs/creating-nodes/properties.md

It seems to be an object and not an array. Or am I missing something?

changed array to object in creating-nodes docs

---

docs/api/ui/editableList/index.md
docs/creating-nodes/config-nodes.md
docs/creating-nodes/help-style-guide.md

Undocumented features in code
header
height:auto
addItems
node-red/editor/js/ui/common/editableList.js
line 54:
if (this.options.header) {
this.options.header.addClass("red-ui-editableList-header");
this.borderContainer = this.uiContainer.wrap("<div>").parent();
this.borderContainer.prepend(this.options.header);
this.topContainer = this.borderContainer.wrap("<div>").parent();
} else {
line 119:
if (this.options.height !== 'auto') {
this.uiContainer.css("overflow-y","scroll");
if (!isNaN(this.options.height)) {
this.uiHeight = this.options.height;
}
}
line 291:
addItems: function(items) {
for (var i=0; i<items.length;i++) {
this.addItem(items[i]);
}
},

Add documentation for EditableList method addItems

---

docs/creating-nodes/properties.md

Also replaced the JavaScript syntax hint with the current GitHub backtick notation.

Clarify the validation function while editing a node

---

docs/creating-nodes/appearance.md

I suggest to double the recommended icon size, 20x30 leads to a blurry look on HiDPI (e.g. Apple Retina) displays. With 40x60 they stay sharp on 2x image rendering.

Double Icon Size

---

docs/platforms/docker.md

Fix the docker latest-v8 tag to v8 to match the actual tags in the repo.

Fix docker tag latest-v8 -> v8

---

docs/getting-started/installation.md

https://nodered.org/docs/getting-started/installation
The command for starting Node-RED was changed with updating to ver 0.20.
I modified the command line of document "Installation".
```
grunt build
node red
```
↓
```
grunt build
npm start
```

modify doc Installation for ver 0.20

---

docs/api/ui/editableList/index.md

I found that there's a typo in the documentation for editableList. I modified the typo.

Fix typo in the documentation for editableList

---

_posts/2019-09-30-version-1-0-released.md

Because the link for the `node-red-contrib-theme-midnight-red` module is invalid currently, I corrected it.  I think that the author kindly changed v1.0 branch to master branch.

Fix link in blog

---

docs/api/ui/editableList/index.md

console was spelled as "consol".

Line 189, corrected spelling of console

---

docs/creating-nodes/properties.md

A gotcha, that caused me several hours of time, is forgetting to make each property of defaults an object.
If it's not an object, bad things happen and you end up with this error "Cannot use 'in' operator to search for 'required' in jquery" in the console.

Added a troubleshooting note to Property definitions

---

docs/getting-started/beaglebone.md

Debian (10) Buster is required for Node-Red 1.x to be installed with the bb-node-red-installer. The image is currently only available as an SD card IoT image, but there is a simple change that can be made to turn this into an eMMC flasher image: just uncommenting one line in a file in the boot directory.
Contribution discussed with dceejay

Update beaglebone with instructions on creating Buster eMMC flasher image

---

docs/creating-nodes/config-nodes.md
docs/creating-nodes/first-node.md
docs/creating-nodes/help-style-guide.md
docs/creating-nodes/node-html.md

To use HTML linters, I changed `type="text/x-red"` to  `type="text/html"` in document about how to create Node-RED nodes.

Change text/x-red to text/html in node html file

---

docs/user-guide/runtime/configuration.md

Fix paletteCategories order to match the order in the "Version 1.0 released" [blog post](https://nodered.org/blog/2019/09/30/version-1-0-released#reorganised-palette).

Fix paletteCategories order

---

docs/user-guide/editor/workspace/flows.md

This PR is to update the flows documentation, with the new Information Sidebar features to enable/disable flows. This PR is based on - 
https://discourse.nodered.org/t/updating-documentation-to-match-with-node-red-1-1-and-above-features/30651
This is my first ever PR and a baby step of contributing to the Node-RED team and community. I am in the process of understanding NR better and may be having more PRs in future!

Rework user guide for enabling disabling flows

---

docs/developing-flows/documenting-flows.md
docs/developing-flows/flow-structure.md
docs/developing-flows/message-design.md

I fixed typos which I found while translating Flow Development Guide.

Fix typos in Flow Development Guide

---

docs/getting-started/ibmcloud.md

Hello,
currently the Deploy to IBM Cloud button points to this deprecated node-red repository:
https://github.com/ibmets/node-red-bluemix-starter
The following is the new one:
https://github.com/IBM/node-red-app
With this pull request I changed the link in the button and the link directly to the repository.
Cheers Lars

Change deprecated deploy to ibm cloud repository

---

docs/getting-started/docker.md

Fix for issue #186, to update documentation to use a user-defined bridge to allow containers to communicate rather than the deprecated --link option.

updated linking container section to remove --link

---

docs/creating-nodes/node-html.md

This generic behavior was removed for "Reorganise nodes into new categories": https://github.com/node-red/node-red/commit/da6db24f9e584702c973c0845aa53bb0ef1e57b2#diff-a971d819871339d0287b6efe397059030d62e0b81090ead3af6225ef37e18c4cR184
Some nodes like MQTT and HTTP do simplify their labels once in a flow. For example, "mqtt in" is shown in the palette but becomes just "mqtt" when in a flow. But that's a function of those nodes, and not a generic function of the editor.
I also removed the "The type is also used as the label for the node in the palette" line since that appears to only be as a fallback in certain circumstances, and labels are covered in detail elsewhere.

Remove old info about node labels having " in" and " out" stripped off

---

docs/getting-started/local.md

Moved boxes for Pi and RPM up to the top and added one for Windows.
Removed Windows link from box under Installing with npm.

Reorganised start of Running Locally page for clarity.

---

docs/api/ui/typedInput/index.md

For another [pull-request](https://github.com/node-red/node-red/pull/2752), I have added two new methods to the docs:
+ `disable`
+ `disabled`
But I saw that there was some other stuff missing, so I have added that also:
+ Types `cred`, `jsonata` and `node`
+ Methods `show` and `hide`
But perhaps we should add in the docs in which version of Node-RED those features have been introduced?
For example the `disable` option in version ***1.3.0*** (?), to avoid that developers are confused that they don't have this feature in older versions of Node-RED.
Thanks!!
Bart

TypedInput page up-to-date

---

docs/user-guide/runtime/securing-node-red.md

I added documentation about how to use `express-rate-limit` module as an example of middleware for http-in node. I think that this knowhow is essential for backend API use case to protect Node-RED instance simply.
The discussion slide is available on the following URL.
https://github.com/node-red-hitachi/node-red-notes/blob/master/Teleconference/20201124/09-Documents.pdf

Add middleware to limit rate in http-in node

---

docs/user-guide/runtime/configuration.md

Adds missing example items mentioned in #257 to the documentation.

Add theme and codeEditor to the configuration example

---

docs/api/ui/autoComplete/index.md

Minor itty-bitty thing: Copy-pasting the example did not produce a red highlight as the css delimiter was set to comma instead of semi-colon.

Changed css delimiter to semi-colon

---

docs/getting-started/flowforge.md
docs/getting-started/index.md
index.html

As a user one might either use the FlowForge Cloud offering, or install
FlowForge themselfs to scale and manage their Node-RED roll out.
This change mentions both options in the appropriate places.

docs: Getting started with FlowForge

---

docs/user-guide/nodes.md

Markdown parses text blocks as continous as long as there's just one new line inserted. This means that `***` which might be intended as a `<hr>` doesn't get rendered when there's no blank line before it, and is interpreted as text.

docs: Fix HR in Markdown

---

docs/api/admin/methods/get/diagnostics/index.md
docs/api/admin/methods/get/flows/state/index.md
docs/api/admin/methods/index.md
docs/api/admin/methods/post/flows/state/index.md

This PR closes #301, closes #303  by documenting the following:
- Keep structure of documentation similar to `/settings`.
- Add a note that `/diagnostics` endpoint is available only when `settings.js` has `diagnostics` option enabled
- add the `GET /diagnostics` endpoint in the API table
- Add API documentation for HTTP GET /flows/state
- Add API documentation for HTTP POST /flows/state
Signed-off-by: Shantanoo 'Shan' Desai <shantanoo.desai@gmail.com>

docs: add API documentation for /diagnostics and /flows/state

---

docs/creating-nodes/appearance.md
docs/creating-nodes/first-node.md

From Node-RED v1.0, the core icons are changed to SVG format. The PNG icon definitions still work, but I thought that the sample code should have an SVG icon in case node developers develop the new node from the official document and extend the functionality.

Replace PNG icon with SVG icon in node development document

---

docs/api/ui/editableList/index.md

This PR adds description of new `cancel` method of editableList that is introduced from Node-RED 3.1 beta2.

add document for cancel operation of editableList

---

docs/faq/node-versions.md

In the 3.1 blog post it states 18 or 20 are the recommended versions, and as such this change updates the main docs.

Update supported Node versions

---

docs/user-guide/writing-functions.md

there is a bracket missing in multiple flow context set call

Update user-guide/writing-functions.md: adding missing close square bracket

---

docs/user-guide/runtime/configuration.md

Adds `httpStaticCors` and `httpAdminCookieOptions` to the docs

Add static cors and cookie options to docs

---

_data/contributors.yml

Thank you for posting our profiles on the Node-RED website. However, the URLs for the corporate websites are invalid. Therefore, I corrected them in this pull request.

Update website URLs of Hitachi members

---

_includes/header.html

Reverts node-red/node-red.github.io#387 now that the survey has closed, the survey callout banner is no longer necessary.

Remove "Survey banner"
